name: Deployment

concurrency: production

on:
  push:
    branches:
      - master


jobs:
  upload_to_server:
    name: push code to server
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "PLACE_HOLDER"

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST_NAME }} >> ~/.ssh/known_hosts

      - name: pull code into server
        run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST_NAME }} 'cd interview1 ; git stash ; git pull origin master'

      - name: run axillary commands
        run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST_NAME }} 'cd interview1 ; composer i ; php artisan migrate'


